# Generated by Django 4.1.3 on 2022-12-12 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAmountSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_from_sales', models.DecimalField(decimal_places=2, max_digits=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_sales', to='business_area.businessmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sold', models.CharField(max_length=256)),
                ('product_category', models.CharField(max_length=256)),
                ('price_of_product', models.DecimalField(decimal_places=2, max_digits=256)),
                ('price_sold_at', models.DecimalField(decimal_places=2, max_digits=256)),
                ('quantity_sold', models.IntegerField()),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_sales', to='business_area.businessmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
