# Generated by Django 4.1.3 on 2023-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=255),
        ),
        migrations.DeleteModel(
            name='TotalAmountSold',
        ),
    ]
