# Generated by Django 4.1.3 on 2022-12-10 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=356)),
                ('business_type', models.CharField(max_length=256)),
                ('business_form', models.CharField(max_length=256)),
                ('business_specialization', models.CharField(max_length=256)),
                ('number_of_employees', models.IntegerField()),
                ('average_annual_profit', models.DecimalField(decimal_places=2, max_digits=256)),
                ('average_annual_budget', models.DecimalField(decimal_places=2, max_digits=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
