# Generated by Django 4.1.3 on 2022-12-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.CharField(default='Clothing', max_length=256),
        ),
    ]
